<link rel="stylesheet" href="css/admin_panel.css" type="text/css">
<link rel="stylesheet" href="css/image_upload_style.css" type="text/css">
<link rel="stylesheet" href="css/jquery-ui.css" type="text/css">
<link rel="stylesheet" href="css/style.css" type="text/css">
<link rel="stylesheet" href='css/pagination.css' type="text/css">
<script type="text/javascript" src="script/jquery.form.min.js" language="javascript"></script>
<script type="text/javascript" src="script/jquery.js" language="javascript"></script>
<script type="text/javascript" src="script/jquery1.10.2.min.js" language="javascript"></script>
<script type="text/javascript" src="script/jquery-ui.min.js" language="javascript"></script>
<script type="text/javascript" src="script/1.7.jquery.min.js" language="javascript"></script>
